### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by frivermen** [ruthsarian/at89c2051_clock#1]
Hello! I'm trying to compile through sdcc 4.2.0, but this do error. What I'm doing wrong?

![изображение](https://user-images.githubusercontent.com/58063894/184337170-1faf7975-21b4-48b9-8d4b-301ffaece7ff.png)

**Comment by ruthsarian** [comment]
This error is caused by the build directory not existing.

I've updated the project to include an empty build directory. I have also updated the Makefile so that it'll create the build directory if it does not exist.
